services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: home-backend
    ports:
      - "2001:2001"
    environment:
      - RUST_LOG=info
    env_file:
      - ./backend/.env.backend
    networks:
      - home-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: home-frontend
    ports:
      - "2000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - PUBLIC_BACKEND_URL=http://0.0.0.0:2001
    networks:
      - home-network
    restart: unless-stopped

networks:
  home-network:
    driver: bridge
